### ISSUE TITLE
pipline方式和无法获取构建状态

### ISSUE THREAD

**Issue by fency12** [binhuang01/FeiShu-Notification#2]
pipline脚本式如下：
stages {
    stage('测试成功失败') {
        steps {
            sh 'echo 不能失败啊'
        }
    }
    stage('发送飞书消息') {
        steps {
            FeiShu(webhook:'https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxx8',proxy:'',msg:'',type:'',atAll:false)
            // 下面失败和成功上面都会通知
        }
    }
}

执行结果如下图：
<img width="719" alt="图片" src="https://user-images.githubusercontent.com/19307432/202137518-42fec926-c804-4f15-9420-0adf636e394e.png">
<img width="628" alt="图片" src="https://user-images.githubusercontent.com/19307432/202137484-37577fc1-dc99-4967-8b50-43be71978a9b.png">

问题：
1、pipline通知到jenkins如法获取构建状态？
2、如果上面的stage内的steps构建失败，下面的通知并不会执行，这个如何解决？

**Comment by fency12** [comment]
stages {
        stage('测试成功失败') {
            steps {
                sh 'echo 不能失败啊'
            }
        }
        stage('发送飞书消息') {
            steps {
                FeiShu(webhook:'https://open.feishu.cn/open-apis/bot/v2/hook/5c38742f-6ae6-4b3e-a42e-3136bc5590c8',proxy:'',msg:'',type:'',atAll:false)
                // 下面失败和成功上面都会通知
            }
        }
    }

已解决

**Comment by fency12** [comment]
1

**Comment by fency12** [comment]
stages {
        stage('测试成功失败') {
            steps {
                sh 'echo 不能失败啊'
            }
        }
        stage('发送飞书消息') {
            steps {
                FeiShu(webhook:'https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxc8',proxy:'',msg:'',type:'',atAll:false)
                // 下面失败和成功上面都会通知
            }
        }
    }

**Comment by binhuang01** [comment]
如果使用声明式语法，请在stages代码块后面添加post后置块显式指定捕获错误，例如
`post {
     failure {
        FeiShu(webhook:'',proxy:'',message:'',atAll:false)
    }
}`

如果想要获取流水线某个阶段的构建状态，应该用warn（需要jenkins版本较新）或catchError块包起来，例如
`catchError(message:'xxx',buildResult:'failure',stageResult:'unstable') {
    FeiShu(webhook:'',proxy:'',message:'',atAll:false)
}`

**Comment by fency12** [comment]
> 
好的已解决。谢谢大佬
